version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 76315631
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin
  app:
    image: api
    ports:
      - "8000:8000"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 76315631
    networks:
      - mysql-phpmyadmin
    ports:
      - "8080:80"
networks:
  mysql-phpmyadmin: