# version: "3.8"

# services:
#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: 76315631
#     ports:
#       - "3306:3306"
#   app:
#     image: api
#     ports:
#       - "8000:8000"

version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 76315631
    ports:
      - "3306:3306"
  app:
    image: api
    ports:
      - "8000:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:8080"
